-- Your SQL goes here

CREATE TABLE users (
  id BIGINT NOT NULL PRIMARY KEY,

  username VARCHAR NOT NULL UNIQUE,
  email VARCHAR(254) UNIQUE,
  password_hash CHAR(97) NOT NULL,

  display_name VARCHAR(50) NOT NULL DEFAULT '',
  has_pfp BOOLEAN NOT NULL DEFAULT FALSE,
  has_banner BOOLEAN NOT NULL DEFAULT FALSE,
  custom_status VARCHAR(50),
  about_me VARCHAR(500) NOT NULL DEFAULT '',

  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_online TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
